// Layout Type
export const HANDLE_MENU_COLLAPSED = "HANDLE_MENU_COLLAPSED"
export const HANDLE_LOADING = "HANDLE_LOADING"

// Accounts Types
export const SET_SETTING_REQUEST = "SET_SETTING_REQUEST"
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS"
export const SET_LATEST_BLOCK_NUMBER = "SET_LATEST_BLOCK_NUMBER"
export const SET_WALET_TYPE = "SET_WALET_TYPE"

// Vault Types
export const SET_AVAILABLE_YAI = "SET_AVAILABLE_YAI"
export const SET_ALLOWANCE_YAI = "SET_ALLOWANCE_YAI"
export const SET_YAI_VAULT_DAW_BALANCE = "SET_YAI_VAULT_DAW_BALANCE"
export const SET_YAI_AMOUNT = "SET_YAI_AMOUNT"
export const SET_YAI_REWARDS = "SET_YAI_REWARDS"
export const SET_DSWAP_BALANCE = "SET_DSWAP_BALANCE"

// Dashboard Types
export const SET_COIN_LIST = "SET_COIN_LIST"
export const SET_COIN_DETAILS = "SET_COIN_DETAILS"
export const SET_GRAPH_DATA="SET_GRAPH_DATA"
export const SET_COIN_PRICE_LIST = "SET_COIN_PRICE_LIST"
export const SET_COIN_WALLET_BALANCE = "SET_COIN_WALLET_BALANCE"
export const SET_COIN_SUPPLY_BALANCE = "SET_COIN_SUPPLY_BALANCE"
export const SET_COIN_BORROW_BALANCE = "SET_COIN_BORROW_BALANCE"
export const SET_COIN_DETAILS_CACHE = "SET_COIN_DETAILS_CACHE"
export const SET_IS_COIN_ENABLED = "SET_IS_COIN_ENABLED"
export const SET_COLLATERAL_VALUE="SET_COLLATERAL_VALUE"
export const SET_POP_TAB_VALUE = "SET_POP_TAB_VALUE"
export const SET_SUPPLY_VALUES = "SET_SUPPLY_VALUES"
export const SET_SUPPLY_WITHDRAW_VALUE = "SET_SUPPLY_WITHDRAW_VALUE"
export const SET_BORROW_VALUES = "SET_BORROW_VALUES"
export const SET_BORROW_REPAY_VALUE = "SET_BORROW_REPAY_VALUE"
export const SET_AVAILABLE_CREDIT = "SET_AVAILABLE_CREDIT"
export const SET_AVAILABLE_CREDIT_PERCENTAGE = "SET_AVAILABLE_CREDIT_PERCENTAGE"
export const SET_AVAILABLE_YAI_LIMIT= "SET_AVAILABLE_YAI_LIMIT"
export const SET_AVAILABLE_YAI_MINTED= "SET_AVAILABLE_YAI_MINTED"
export const SET_YAI_APPROVED="SET_YAI_APPROVED"

// Price list Types
export const SET_COIN_PRICE_DATA="SET_COIN_PRICE_DATA"