// Layout Type
export const HANDLE_MENU_COLLAPSED = "HANDLE_MENU_COLLAPSED"
export const HANDLE_LOADING = "HANDLE_LOADING"

// Tost types
export const SHOW_TOAST_NOFITICATION = "SHOW_TOAST_NOFITICATION"
export const REMOVE_TOAST_NOFITICATION = "REMOVE_TOAST_NOFITICATION"

// Accounts Types
export const SET_SETTING_REQUEST = "SET_SETTING_REQUEST"

// Vault Types
export const SET_AVAILABLE_YAI = "SET_AVAILABLE_YAI"
export const SET_ALLOWANCE_YAI = "SET_ALLOWANCE_YAI"
export const SET_YAI_VAULT_DAW_BALANCE = "SET_YAI_VAULT_DAW_BALANCE"
export const SET_YAI_AMOUNT = "SET_YAI_AMOUNT"
export const SET_YAI_REWARDS = "SET_YAI_REWARDS"
export const SET_DSWAP_BALANCE = "SET_DSWAP_BALANCE"